### ISSUE TITLE
Shouldn't `push_pop_min` and `replace_min` be the same function?

### ISSUE THREAD

**Issue by robinmoussu** [tov/min-max-heap-rs#9]
I was looking at the implementation of [push_pop_min](https://docs.rs/min-max-heap/1.3.0/src/min_max_heap/lib.rs.html#197-205) and [replace_min](https://docs.rs/min-max-heap/1.3.0/src/min_max_heap/lib.rs.html#233-242) and was expected to see more or less the same thing.

However, when the min-max-head is empty, `push_pop_min` will **not** push the element. It look like it's a bug.

Also, I don't understand why two functions are needed. I would have thought that one would be an alias to the other. The documentation doesn't explain why two of them are needed.

**Comment by tov** [comment]
Except for avoiding allocation, push_pop_min is equivalent to push followed by pop_min, whereas replace_min is equivalent to pop_min followed by push. This implies that if the element you give it is smaller than anything already in the heap, push_pop_min gives you back the element you just gave it, whereas replace_min always leaves the element you give it in the heap and gives you back the *old* minimum element.

If the heap is empty, then the correct behavior for push_pop_min is to return its argument and leave the heap empty, because that is what push followed by pop_min would do. On the other hand, replace_min pushes the element and returns `None`, which is what pop_min followed by push would do.

It might be good if the documentation made this all clearer.

**Comment by robinmoussu** [comment]
Perfect explanation, thanks.
